prop(probe, mineral, 50).
prop(probe, gas, 0).
prop(probe, armour, 0).
prop(probe, hp, 20).
prop(probe, shield, 20).
prop(probe, race, protoss).
prop(probe, attributeModifier, [light,mechanical]).
prop(probe, groundAttack, 5).
prop(probe, bonusAttack, 0).
prop(probe, bonusType, []).
prop(probe, coolDown, 1.07).
prop(probe, range, 0).
prop(probe, speed, 3.94).

prop(zealot, mineral, 100).
prop(zealot, gas, 0).
prop(zealot, armour, 1).
prop(zealot, hp, 100).
prop(zealot, shield, 50).
prop(zealot, race, protoss).
prop(zealot, attributeModifier, [light,biological]).
prop(zealot, groundAttack, 16).
prop(zealot, bonusAttack, 0).
prop(zealot, bonusType, []).
prop(zealot, coolDown, 0.86).
prop(zealot, range, 0).
prop(zealot, speed, 3.15).

prop(sentry, mineral, 50).
prop(sentry, gas, 100).
prop(sentry, armour, 1).
prop(sentry, hp, 40).
prop(sentry, shield, 40).
prop(sentry, race, protoss).
prop(sentry, attributeModifier, [light,mechanical,psionic]).
prop(sentry, groundAttack, 6).
prop(sentry, bonusAttack, 0).
prop(sentry, bonusType, []).
prop(sentry, coolDown, 0.71).
prop(sentry, range, 5).
prop(sentry, speed, 3.15).

prop(stalker, mineral, 125).
prop(stalker, gas, 50).
prop(stalker, armour, 1).
prop(stalker, hp, 80).
prop(stalker, shield, 80).
prop(stalker, race, protoss).
prop(stalker, attributeModifier, [armoured,mechanical]).
prop(stalker, groundAttack, 10).
prop(stalker, bonusAttack, 4).
prop(stalker, bonusType, [armoured]).
prop(stalker, coolDown, 1.03).
prop(stalker, range, 6).
prop(stalker, speed, 4.13).

prop(adept, mineral, 100).
prop(adept, gas, 25).
prop(adept, armour, 1).
prop(adept, hp, 70).
prop(adept, shield, 70).
prop(adept, race, protoss).
prop(adept, attributeModifier, [light,biological]).
prop(adept, groundAttack, 10).
prop(adept, bonusAttack, 12).
prop(adept, bonusType, [light]).
prop(adept, coolDown, 1.61).
prop(adept, range, 4).
prop(adept, speed, 3.5).

prop(darkTemplar, mineral, 125).
prop(darkTemplar, gas, 125).
prop(darkTemplar, armour, 1).
prop(darkTemplar, hp, 40).
prop(darkTemplar, shield, 80).
prop(darkTemplar, race, protoss).
prop(darkTemplar, attributeModifier, [light,biological,psionic]).
prop(darkTemplar, groundAttack, 10).
prop(darkTemplar, bonusAttack, 12).
prop(darkTemplar, bonusType, [light]).
prop(darkTemplar, coolDown, 1.61).
prop(darkTemplar, range, 4).
prop(darkTemplar, speed, 3.5).

prop(immortal, mineral, 250).
prop(immortal, gas, 100).
prop(immortal, armour, 1).
prop(immortal, hp, 200).
prop(immortal, shield, 100).
prop(immortal, race, protoss).
prop(immortal, attributeModifier, [armoured,mechanical]).
prop(immortal, groundAttack, 20).
prop(immortal, bonusAttack, 30).
prop(immortal, bonusType, [armoured]).
prop(immortal, coolDown, 1.04).
prop(immortal, range, 6).
prop(immortal, speed, 3.15).

prop(colossus, mineral, 300).
prop(colossus, gas, 200).
prop(colossus, armour, 1).
prop(colossus, hp, 200).
prop(colossus, shield, 150).
prop(colossus, race, protoss).
prop(colossus, attributeModifier, [armoured,mechanical,massive]).
prop(colossus, groundAttack, 12).
prop(colossus, bonusAttack, 0).
prop(colossus, bonusType, []).
prop(colossus, coolDown, 1.18).
prop(colossus, range, 6).
prop(colossus, speed, 3.15).