prop(drone, mineral, 50).
prop(drone, gas, 0).
prop(drone, armour, 0).
prop(drone, hp, 40).
prop(drone, shield, 0).
prop(drone, race, zerg).
prop(drone, attributeModifier, [light,biological]).
prop(drone, groundAttack, 5).
prop(drone, bonusAttack, 0).
prop(drone, bonusType, []).
prop(drone, coolDown, 1.07).
prop(drone, range, 0).
prop(drone, speed, 3.94).

prop(queen, mineral, 150).
prop(queen, gas, 0).
prop(queen, armour, 1).
prop(queen, hp, 175).
prop(queen, shield, 0).
prop(queen, race, zerg).
prop(queen, attributeModifier, [biological,psionic]).
prop(queen, groundAttack, 8).
prop(queen, bonusAttack, 0).
prop(queen, bonusType, []).
prop(queen, coolDown, 0.71).
prop(queen, range, 5).
prop(queen, speed, 1.31).

prop(zergling, mineral, 25).
prop(zergling, gas, 0).
prop(zergling, armour, 0).
prop(zergling, hp, 35).
prop(zergling, shield, 0).
prop(zergling, race, zerg).
prop(zergling, attributeModifier, [light,biological]).
prop(zergling, groundAttack, 5).
prop(zergling, bonusAttack, 0).
prop(zergling, bonusType, []).
prop(zergling, coolDown, 0.497).
prop(zergling, range, 0).
prop(zergling, speed, 4.13).

prop(roach, mineral, 75).
prop(roach, gas, 25).
prop(roach, armour, 1).
prop(roach, hp, 145).
prop(roach, shield, 0).
prop(roach, race, zerg).
prop(roach, attributeModifier, [biological]).
prop(roach, groundAttack, 16).
prop(roach, bonusAttack, 0).
prop(roach, bonusType, []).
prop(roach, coolDown, 1.14).
prop(roach, range, 6).
prop(roach, speed, 3.85).

prop(ravager, mineral, 25).
prop(ravager, gas, 75).
prop(ravager, armour, 1).
prop(ravager, hp, 120).
prop(ravager, shield, 0).
prop(ravager, race, zerg).
prop(ravager, attributeModifier, [armoured,biological]).
prop(ravager, groundAttack, 16).
prop(ravager, bonusAttack, 0).
prop(ravager, bonusType, []).
prop(ravager, coolDown, 1.43).
prop(ravager, range, 4).
prop(ravager, speed, 3.15).

prop(hydralisk, mineral, 100).
prop(hydralisk, gas, 50).
prop(hydralisk, armour, 0).
prop(hydralisk, hp, 90).
prop(hydralisk, shield, 0).
prop(hydralisk, race, zerg).
prop(hydralisk, attributeModifier, [light,biological]).
prop(hydralisk, groundAttack, 12).
prop(hydralisk, bonusAttack, 0).
prop(hydralisk, bonusType, []).
prop(hydralisk, coolDown, 0.54).
prop(hydralisk, range, 5).
prop(hydralisk, speed, 3.15).

prop(ultralisk, mineral, 300).
prop(ultralisk, gas, 200).
prop(ultralisk, armour, 2).
prop(ultralisk, hp, 500).
prop(ultralisk, shield, 0).
prop(ultralisk, race, zerg).
prop(ultralisk, attributeModifier, [armoured,biological,massive]).
prop(ultralisk, groundAttack, 35).
prop(ultralisk, bonusAttack, 0).
prop(ultralisk, bonusType, []).
prop(ultralisk, coolDown, 0.61).
prop(ultralisk, range, 1).
prop(ultralisk, speed, 4.13).
